/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tictactoe;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        MainApp classUnderTest = new MainApp();
    }
}
